#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuka
  labels:
    app: chuka
spec:
 replicas: 2
 selector:
   matchLabels:
     app: chuka
 template:
   metadata:
     labels:
       app: chuka
   spec:
     containers:
     - name: chuka-con
       image: workspacebychuka/devops:2 #manually change tag number of build, if it doest work try :latest
       imagePullPolicy: "Always"
       ports:
       - containerPort: 8080
