#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuka
  labels:
    app: chuka
spec:
 replicas: 2
 selector:
   matchLabels:
     app: chuka
 template:
   metadata:
     labels:
       app: chuka
   spec:
     containers:
     - name: chuka-con
       image: workspacebychuka/devops:latest #edit image but leave :latest as make variable remain interacting with jenkinsfile {BUILD_NUMBER}
       ports:
       - containerPort: 8080
