#Create Custom Container Image, and Push it to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    get_url: 
      url: http://34.193.121.219:8082/artifactory/devops-project-libs-release-local/com/theITern/theITern/1.0-RELEASE/theITern-1.0-RELEASE.war
      dest: /home/ec2-user
      url_username: admin
      url_password: Iamchasingdream$1

  - name: Rename .war Artifact
    command: mv -f theITern-1.0-RELEASE.war webapp.war
  
  - name: make sure python docker library is there for the docker_image module execution
    ansible.builtin.pip:
      name: docker
      
  - name: install docker engine
    apt:
      pkg:
      - docker
      - docker.io
    become: yes

  - name: Pull Tomcat  Container Image
    docker_image:
      name: !unsafe tomcat:latest
      source: pull
      force_tag: yes

  - name: Build image and with build args
    docker_image:
      name: workspacebychuka/devops
      repository: workspacebychuka/devops:{{build_number}}
      build:
        path: /home/ec2-user
        args:
          listen_port: 8080
      source: build
      force_source: yes
  
  
  - name: Log into DockerHub
    docker_login:
     username: workspacebychuka@gmail.com
     password: Iamzebra1
 

  - name: Push to docker hub
    docker_image:
        name: workspacebychuka/devops
        repository: workspacebychuka/devops:{{build_number}}
        force_tag: yes
        push: yes
        source: local
    
